# Generated by Django 5.0.2 on 2024-07-23 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
